// https://leetcode.com/problems/find-the-difference/#/description
// 389. Find the Difference
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
#import <iostream>
#import <string>

using namespace std;

class Solution26 {
public:
    char findTheDifference(string s, string t) {
        char result = '\0';
        for (auto c : s) {
            result ^= c;
        }
        for (auto c : t) {
            result ^= c;
        }

        return result;
    }

    void test() {
        auto inputS = string("abcd");
        auto inputT = string("abcde");
        auto output = this->findTheDifference(inputS, inputT);
        cout << "389. Find the Difference : " << output << endl;
    }
};
